steps:

- id: "Docker-compose - Executando"
  name: 'gcr.io/$PROJECT_ID/docker-compose'
  args: ['-f','docker-compose.cloudbuild.yaml','up','-d']

- id: "Dockerc ps - Executando"
  name: 'gcr.io/cloud-builders/docker'
  args: ['ps']

- id: "Composer - Executando"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-t','workspace_php_1','composer','install']

- id: "Copiando .env - Executando"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-t','workspace_php_1','cp','.env-production','.env']

- id: "Key generate - Executando"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-t','workspace_php_1','php','/var/www/artinsan','key:generate']

- id: "Migrations - Executando"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-t','workspace_php_1','php','/var/www/artinsan','migrate']

- id: "PhpUnit - Executando"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-t','workspace_php_1','php','/var/www/vendor/vendor/bin/phpunit','-c','/var/www/phpunit.xml']
