version: "3"

networks:
  rede-privada:
    driver: bridge

services:
  app:
    build:
      context: ./.docker/builds
      dockerfile: Dockerfile-php
    volumes:
      - .:/var/www
      - /etc/localtime:/etc/localtime
    networks:
      - rede-privada
    depends_on:
      - db57
      - redis
  nginx:
    build:
      dockerfile: ./.docker/builds/Dockerfile-nginx
      context: .
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    # entrypoint: dockerize -template ./.docker/templates/nginx-laravel.conf:/etc/nginx/conf.d/default.conf nginx -g 'daemon off;'
    environment:
      - FPM_SERVICE=php
      - FPM_PORT=9000
    volumes:
      - .:/var/www
      - /etc/localtime:/etc/localtime
    networks:
      - rede-privada
    depends_on:
      - app
  db57:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db57
    restart: always
    tty: true
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_DATABASE: curso
      MYSQL_ROOT_PASSWORD: root
    networks:
      - rede-privada
  redis:
    image: redis:alpine
    volumes:
      - ./.docker/redis/data:/data
      - /etc/localtime:/etc/localtime
    networks:
      - rede-privada
