FROM php:7.4-fpm

WORKDIR /var/www

RUN apt-get update && apt-get install -y zlib1g-dev libzip-dev \
    && docker-php-ext-install pdo pdo_mysql zip \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && apt-get clean \
    && rm -rf /var/www/html \
    && pecl install -o -f redis \
    && rm -rf /tmp/pear \
    && docker-php-ext-enable redis

ADD https://getcomposer.org/composer-stable.phar /usr/bin/composer

RUN chmod 755 /usr/bin/composer

EXPOSE 9000
ENTRYPOINT ["php-fpm"]
